name: test
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
    - uses: actions/checkout@v3
    - run: cd ${{ github.workspace }}/week05/Chapter15 && go test ./... -coverprofile=coverage.out
    - name: report coverage
      uses: k1LoW/octocov-action@v0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}